function Photography() {
    return (
        <div className="content">
            <h1>Photography</h1>
            <hr></hr>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
            <p>yo</p>
        </div>
    )
}

export default Photography